# Generated by Django 3.0.3 on 2020-02-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testDescription', models.CharField(max_length=264)),
                ('severity', models.CharField(max_length=50)),
                ('ipaddress', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=50)),
                ('commandExecuter', models.CharField(max_length=264)),
                ('verdict', models.CharField(max_length=264)),
                ('remark', models.CharField(max_length=264)),
                ('testId', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
